---
# tasks file for ipmitool
#

- name: install ipmitool
  package: name=freeipmi state=latest

- name: install ipmitool
  package: name=ipmitool state=latest

- name: detect if the system supports IPMI via Inband communication
  shell: "ipmi-locate | grep done"
  register: ipmi_locate

- name: install ipmi kernel module and config ipmi
  include: "tasks/install_and_config.yml"
  when: ipmi_locate.stdout != ""
